"""create environment tables

Revision ID: 467c696c9829
Revises: 
Create Date: 2026-02-25 23:48:55.588396
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '467c696c9829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource_group', sa.String(length=255), nullable=False),
    sa.Column('frontend_app_name', sa.String(length=255), nullable=False),
    sa.Column('backend_app_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), server_default='DEV', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_apps_id'), 'environment_apps', ['id'], unique=False)
    op.create_index(op.f('ix_environment_apps_name'), 'environment_apps', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environment_apps_name'), table_name='environment_apps')
    op.drop_index(op.f('ix_environment_apps_id'), table_name='environment_apps')
    op.drop_table('environment_apps')
    # ### end Alembic commands ###
